"""empty message

Revision ID: d732058df32c
Revises: 0f6b9f8ccade
Create Date: 2025-05-15 21:39:39.032196

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd732058df32c'
down_revision: Union[str, None] = '0f6b9f8ccade'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_auth',
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('privilage', postgresql.ENUM('ADMIN', 'USER', name='userprivileges'), server_default=sa.text("'USER'::userprivileges"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_auth_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_auth_pkey')
    )
    # ### end Alembic commands ###
